### ISSUE TITLE
Fix application of material effects

### ISSUE THREAD

**Issue by kmcdermo** [trackreco/mkFit#194]
As discussed in PR #190, there is room for improvement when applying the material effects. On the docket for relatively straightforward-to-implement changes are the following:

1) When in a split stereo layer, skip applying material effects in propagation to 2nd part of split layer if the 1st split layer had material effects applied.
2) Use dot product of dR/|dZ| + track momentum to apply correct material constants when going forward or backward.

To achieve 1), we can code this into the layer plan, which will have a flag to skip material effects if on the second half of a split layer. However, if we miss a hit on the previous layer, no material effects will be applied for this layer.

This technicality was actually already mentioned in the PR: if we do not find a hit on a layer n, add then propagate to n+1, the material effects are applied for only n -> n+1, where it should be n-1 -> n+1 (i.e. integrate the full material passed). This is a non-trivial task to make such a tool but could be done.  Would require a look-up of last layers, then getting the material constants for each, and then applying the constants in one fell swoop.

**Comment by areinsvo** [comment]
**First**, I want to document the effect of the one-line change [here](https://github.com/trackreco/mkFit/blob/devel/mkFit/PropagationMPlex.cc#L724) before adding it to Pandora's box: current baseline plots are [here](http://areinsvo.web.cern.ch/areinsvo/MkFit/ChargeAssignment/April2020/baseline), and plots including the change to the material effects calculation are [here](http://areinsvo.web.cern.ch/areinsvo/MkFit/ChargeAssignment/April2020/fixedEndcapMaterial).

The fake rate and efficiency actually improve with this change (eff increases by 0.6% overall, which is a noticeable improvement in the endcaps), but the duplicate rate goes from 7.9 to 9.8% and the number of hits for the best match track drops from 14.3 to 13.9 hits.  There is also a noticeable improvement in the tails of the eta residuals.

Before:
![EtaDiff_baseline](https://user-images.githubusercontent.com/7669806/83546916-11111200-a4c7-11ea-9bac-9645a2144334.png)

After:
![EtaDiff_fixedEndcapMaterial](https://user-images.githubusercontent.com/7669806/83546925-140c0280-a4c7-11ea-93cf-7f5a0fde77f9.png)

**Second**, for the record: item (2) described at the beginning of this issue was fixed a while ago by Giuseppe by adding the [propSign](https://github.com/trackreco/mkFit/blob/devel/mkFit/PropagationMPlex.cc#L705) parameter to the applyMaterialEffects function. 

**Third**, as mentioned in last Friday's meeting, I'm going to investigate item (1) and double check how we apply the material constants for mono/stereo layers.

**Comment by areinsvo** [comment]
As far as I can tell, all of this was resolved in Pandora's Box, which is now merged into devel. Closing this issue.
